name = "llm-todo"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "llm-todo"
database_id = "local"
migrations_dir = "drizzle/migrations"
